document.addEventListener('DOMContentLoaded', () => {
    const questions = [
        { question: "Can a paradox be resolved?", answers: ["Yes", "No", "Only in specific cases", "Not sure"], correct: 0 },
        { question: "If a statement is both true and false, can it be true?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "Is the Liar Paradox resolvable?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 1 },
        { question: "Can the Grandfather Paradox be avoided?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 1 },
        { question: "Can a paradox be created by altering definitions?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change the past, would it change the present?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 1 },
        { question: "Can a paradox exist in a logically consistent system?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If a statement is both true and false, can it be resolved?", answers: ["Yes", "No", "Only in certain contexts", "Not sure"], correct: 1 },
        { question: "Can the concept of time travel create paradoxes?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 0 },
        { question: "Is it possible for an event to be both past and future simultaneously?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 1 },
        { question: "Can a paradox be resolved by changing the context of the question?", answers: ["Yes", "No", "Only in specific cases", "Not sure"], correct: 2 },
        { question: "If you know the outcome of an event, does it mean the event is predetermined?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can paradoxes be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you can observe every possible outcome, does it make every outcome real?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it mean every outcome is inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent simultaneously?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its definition?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox exist in a logically consistent system?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing its context or interpretation?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If every possibility exists, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the definition of its terms?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "If you could change every factor, does that imply the future is mutable?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can something be both true and false in different logical systems?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If the universe is infinite, does it mean it contains every possible outcome?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can a paradox be considered resolved if it creates more questions?", answers: ["Yes", "No", "Only if universally accepted", "Not sure"], correct: 1 },
        { question: "If a future event is known, does it mean it was always going to happen?", answers: ["Yes", "No", "Only if determinism is true", "Not sure"], correct: 2 },
        { question: "Can a statement be both accurate and inaccurate simultaneously in different contexts?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it make every outcome inevitable?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by changing the rules of logic?", answers: ["Yes", "No", "Only in specific systems", "Not sure"], correct: 2 },
        { question: "If you could observe every possible outcome, would you still be able to change the future?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "Can something be both existent and non-existent in different contexts simultaneously?", answers: ["Yes", "No", "Only in specific frameworks", "Not sure"], correct: 2 },
        { question: "If you know the exact outcome of every event, does that mean the future is predetermined?", answers: ["Yes", "No", "Only in specific theories", "Not sure"], correct: 2 },
        { question: "Can a paradox be resolved by altering fundamental principles of logic?", answers: ["Yes", "No", "Only in specific models", "Not sure"], correct: 2 },
        { question: "If every possible event occurs, does it mean every outcome is real?", answers: ["Yes", "No", "Only in specific contexts", "Not sure"], correct: 2 }
    ]
}
